PÃ¡gina de referencia: https://datatracker.ietf.org/doc/html/rfc2616.html

('Connection aborted.', BadStatusLine(' OK\r\n'))
('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
200
Accepted
Bad Gateway
Bad Request
Connection refused
Document follows
Exceeded 30 redirects.
Forbidden
Gateway Time-out
Gone
HTTPConnectionPool(host='122.228.158.106', port=80): Max retries exceeded with url: /EpilepsyGene (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5a5a118>, 'Connection to 122.228.158.106 timed out. (connect timeout=120)'))
HTTPConnectionPool(host='149.171.101.136', port=80): Max retries exceeded with url: /python/BloodChIP/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5ae8be0>, 'Connection to 149.171.101.136 timed out. (connect timeout=120)'))
HTTPConnectionPool(host='192.168.0.6', port=80): Max retries exceeded with url: /urlfilter/urlfilter.html?url=pmite.hzau.edu.cn/django/mite/&type=%E6%9C%AA%E5%A4%87%E9%9E%8D%E7%BD%91%E7%AB%99 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5acd5b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
HTTPConnectionPool(host='202.97.205.78', port=80): Max retries exceeded with url: /diseasemeth (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5abed60>, 'Connection to 202.97.205.78 timed out. (connect timeout=120)'))
HTTPConnectionPool(host='2p2idb.cnrs-mrs.fr', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5bfcaf0>, 'Connection to 2p2idb.cnrs-mrs.fr timed out. (connect timeout=120)'))
HTTPConnectionPool(host='47.100.169.139', port=80): Max retries exceeded with url: /tcmid (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5a3e688>: Failed to establish a new connection: [Errno 111] Connection refused'))
HTTPConnectionPool(host='47.100.169.139', port=80): Max retries exceeded with url: /tcmid (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5acdd48>: Failed to establish a new connection: [Errno 111] Connection refused'))
HTTPConnectionPool(host='4dx.embl.de', port=80): Max retries exceeded with url: /4DXpress/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5acdf40>, 'Connection to 4dx.embl.de timed out. (connect timeout=120)'))
HTTPConnectionPool(host='61.148.58.210', port=8080): Max retries exceeded with url: /EpiDenovo/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5b1c7f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
HTTPConnectionPool(host='aagatlas.ncpsb.org', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5a45dd8>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='aclame.ulb.ac.be', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5acd9a0>, 'Connection to aclame.ulb.ac.be timed out. (connect timeout=120)'))
HTTPConnectionPool(host='agd.vital-it.ch', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5b1ce50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='ahd.cbi.pku.edu.cn', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5abeb80>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='annmap.picr.man.ac.uk', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5a45760>, 'Connection to annmap.picr.man.ac.uk timed out. (connect timeout=120)'))
HTTPConnectionPool(host='antares.protres.ru', port=80): Max retries exceeded with url: /comsin/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5bfcb50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='app.mc.uky.edu', port=80): Max retries exceeded with url: /kolab/rogedendo.aspx (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5b1ce50>, 'Connection to app.mc.uky.edu timed out. (connect timeout=120)'))
HTTPConnectionPool(host='appris-tools.org', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5bfc640>, 'Connection to appris-tools.org timed out. (connect timeout=120)'))
HTTPConnectionPool(host='apps.nhlbi.nih.gov', port=80): Max retries exceeded with url: /grasp/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5acdbc8>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='aps.unmc.edu', port=80): Max retries exceeded with url: /AP/main.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5b30508>: Failed to establish a new connection: [Errno 111] Connection refused'))
HTTPConnectionPool(host='archive.broadinstitute.org', port=80): Max retries exceeded with url: /annotation/fungi/magnaporthe (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5ae8b20>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='barcode.luhs.org', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5bfcf58>, 'Connection to barcode.luhs.org timed out. (connect timeout=120)'))
HTTPConnectionPool(host='beamish.ucc.ie', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5a3e448>, 'Connection to beamish.ucc.ie timed out. (connect timeout=120)'))
HTTPConnectionPool(host='benham.genomecenter.ucdavis.edu', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5a45100>, 'Connection to benham.genomecenter.ucdavis.edu timed out. (connect timeout=120)'))
HTTPConnectionPool(host='berry.engin.umich.edu', port=80): Max retries exceeded with url: /oligoarraydb/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5a4d370>, 'Connection to berry.engin.umich.edu timed out. (connect timeout=120)'))
HTTPConnectionPool(host='bidd.nus.edu.sg', port=80): Max retries exceeded with url: /group/cjttd/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5acd928>, 'Connection to bidd.nus.edu.sg timed out. (connect timeout=120)'))
HTTPConnectionPool(host='bidd.nus.edu.sg', port=80): Max retries exceeded with url: /group/drt/dart.asp (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5abec70>, 'Connection to bidd.nus.edu.sg timed out. (connect timeout=120)'))
HTTPConnectionPool(host='bidd.nus.edu.sg', port=80): Max retries exceeded with url: /group/ttd/ttd.asp (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5abe730>, 'Connection to bidd.nus.edu.sg timed out. (connect timeout=120)'))
HTTPConnectionPool(host='bidd2.nus.edu.sg', port=80): Max retries exceeded with url: /NPASS/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5abec28>, 'Connection to bidd2.nus.edu.sg timed out. (connect timeout=120)'))
HTTPConnectionPool(host='bidd2.nus.edu.sg', port=80): Max retries exceeded with url: /cfam (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5ae8520>, 'Connection to bidd2.nus.edu.sg timed out. (connect timeout=120)'))
HTTPConnectionPool(host='bio-cluster.iis.sinica.edu.tw', port=80): Max retries exceeded with url: /TMPad (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5a3e850>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='bioinf.charite.de', port=80): Max retries exceeded with url: /superdrug/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5b1ccd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='bioinfo.hrbmu.edu.cn', port=80): Max retries exceeded with url: /hhmd (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5ae8958>, 'Connection to bioinfo.hrbmu.edu.cn timed out. (connect timeout=120)'))
HTTPConnectionPool(host='bioinfo.protres.ru', port=80): Max retries exceeded with url: /hrap/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5ae8250>: Failed to establish a new connection: [Errno 113] No route to host'))
HTTPConnectionPool(host='bioinfo.tg.fh-giessen.de', port=80): Max retries exceeded with url: /pdbselect/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5a454c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='bioinfobase.umkc.edu', port=80): Max retries exceeded with url: /speed/speed_main.htm (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5a45640>, 'Connection to bioinfobase.umkc.edu timed out. (connect timeout=120)'))
HTTPConnectionPool(host='bioinformatics.breastcancertissuebank.org', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5acd868>: Failed to establish a new connection: [Errno 113] No route to host'))
HTTPConnectionPool(host='bioinformatics.breastcancertissuebank.org', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5b1c340>: Failed to establish a new connection: [Errno 113] No route to host'))
HTTPConnectionPool(host='bioinformatics.ekmd.huji.ac.il', port=80): Max retries exceeded with url: /reptar (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5bfcbe0>, 'Connection to bioinformatics.ekmd.huji.ac.il timed out. (connect timeout=120)'))
HTTPConnectionPool(host='bioinformatics.engineering.asu.edu', port=80): Max retries exceeded with url: /springs/Sprouts/index.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5ae82b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='bioinformatik.wzw.tum.de', port=80): Max retries exceeded with url: /index.php?id=63&L=1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5acd5c8>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='bionemo.bioinfo.cnio.es', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5b305e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='biosrv.cab.unina.it', port=80): Max retries exceeded with url: /tomatestdb/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5acd040>: Failed to establish a new connection: [Errno 113] No route to host'))
HTTPConnectionPool(host='biotech.bmi.ac.cn', port=80): Max retries exceeded with url: /3dsnp/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5a45b98>, 'Connection to biotech.bmi.ac.cn timed out. (connect timeout=120)'))
HTTPConnectionPool(host='biotech.bmi.ac.cn', port=80): Max retries exceeded with url: /ehfpi/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5a5a418>, 'Connection to biotech.bmi.ac.cn timed out. (connect timeout=120)'))
HTTPConnectionPool(host='bioweb.ensam.inra.fr', port=80): Max retries exceeded with url: /spodobase/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5ae8970>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='biozon.org', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5a5a718>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='bird.cbrc.jp', port=80): Max retries exceeded with url: /sahg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5a459e8>, 'Connection to bird.cbrc.jp timed out. (connect timeout=120)'))
HTTPConnectionPool(host='bps.rutgers.edu', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5a5a0a0>, 'Connection to bps.rutgers.edu timed out. (connect timeout=120)'))
HTTPConnectionPool(host='bugs.sgul.ac.uk', port=80): Max retries exceeded with url: /E-BUGS-PUB (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5a5a7a8>, 'Connection to bugs.sgul.ac.uk timed out. (connect timeout=120)'))
HTTPConnectionPool(host='camera.calit2.net', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5a45e38>, 'Connection to camera.calit2.net timed out. (connect timeout=120)'))
HTTPConnectionPool(host='cbs.dtu.dk', port=80): Max retries exceeded with url: /services/NutriChem-1.0 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5ae8340>, 'Connection to cbs.dtu.dk timed out. (connect timeout=120)'))
HTTPConnectionPool(host='ccb1.bmi.ac.cn', port=80): Max retries exceeded with url: /srnatarbase/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5a3ead8>, 'Connection to ccb1.bmi.ac.cn timed out. (connect timeout=120)'))
HTTPConnectionPool(host='cdna01.dna.affrc.go.jp', port=80): Max retries exceeded with url: /PIPE/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5a3eb38>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='cefg.uestc.edu.cn', port=80): Max retries exceeded with url: /anti-CRISPRdb/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5b1c298>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='centrosome.cnb.csic.es', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5ab2f40>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='cgap.nci.nih.gov', port=80): Max retries exceeded with url: /Pathways/BioCarta_Pathways (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5b1c0d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
HTTPConnectionPool(host='cgbc.cgu.edu.tw', port=80): Max retries exceeded with url: /cmpd/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5acdd18>, 'Connection to cgbc.cgu.edu.tw timed out. (connect timeout=120)'))
HTTPConnectionPool(host='cgg.ebi.ac.uk', port=80): Max retries exceeded with url: /cgg/cpp_sitemap.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5ab2f70>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='cgl.imim.es', port=80): Max retries exceeded with url: /fcp/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5a4d928>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='cgsmd.isi.edu', port=80): Max retries exceeded with url: /dbsnpq (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5ab2a30>, 'Connection to cgsmd.isi.edu timed out. (connect timeout=120)'))
HTTPConnectionPool(host='cheminfo.charite.de', port=80): Max retries exceeded with url: /superdrug2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5abe988>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='cheminfo.charite.de', port=80): Max retries exceeded with url: /withdrawn (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5abef10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='chloroplast.cbio.psu.edu', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5acd640>, 'Connection to chloroplast.cbio.psu.edu timed out. (connect timeout=120)'))
HTTPConnectionPool(host='chordate.bpni.bio.keio.ac.jp', port=80): Max retries exceeded with url: /faba/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5a45bf8>, 'Connection to chordate.bpni.bio.keio.ac.jp timed out. (connect timeout=120)'))
HTTPConnectionPool(host='circe.med.uniroma1.it', port=80): Max retries exceeded with url: /digit (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5b30580>, 'Connection to circe.med.uniroma1.it timed out. (connect timeout=120)'))
HTTPConnectionPool(host='circnet.mbc.nctu.edu.tw', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5ab2f40>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='cmbi.bjmu.edu.cn', port=80): Max retries exceeded with url: /Sdisease (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5a3ed78>, 'Connection to cmbi.bjmu.edu.cn timed out. (connect timeout=120)'))
HTTPConnectionPool(host='cmbi.bjmu.edu.cn', port=80): Max retries exceeded with url: /hmdd (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5a3e8c8>, 'Connection to cmbi.bjmu.edu.cn timed out. (connect timeout=120)'))
HTTPConnectionPool(host='cnidarians.bu.edu', port=80): Max retries exceeded with url: /stellabase/index.cgi (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5ae8d90>, 'Connection to cnidarians.bu.edu timed out. (connect timeout=120)'))
HTTPConnectionPool(host='cogeme.ex.ac.uk', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5ab2f40>, 'Connection to cogeme.ex.ac.uk timed out. (connect timeout=120)'))
HTTPConnectionPool(host='combrex.bu.edu', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5b30658>, 'Connection to combrex.bu.edu timed out. (connect timeout=120)'))
HTTPConnectionPool(host='comparasite.hgc.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5b30bb0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='compbio.cs.queensu.ca', port=80): Max retries exceeded with url: /F-SNP/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5a4d130>: Failed to establish a new connection: [Errno 113] No route to host'))
HTTPConnectionPool(host='compbio.dfci.harvard.edu', port=80): Max retries exceeded with url: /genesigdb (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5b1c880>, 'Connection to compbio.dfci.harvard.edu timed out. (connect timeout=120)'))
HTTPConnectionPool(host='cops.igib.res.in', port=80): Max retries exceeded with url: /copsv2/index.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5ab2ec8>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='covdb.microbiology.hku.hk', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5ab2a78>, 'Connection to covdb.microbiology.hku.hk timed out. (connect timeout=120)'))
HTTPConnectionPool(host='cpla.biocuckoo.org', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5b30a18>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='crispviewdatabase.weililab.org', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5ab2820>: Failed to establish a new connection: [Errno 111] Connection refused'))
HTTPConnectionPool(host='cse-mnm.engr.uconn.edu', port=8080): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5a3e760>: Failed to establish a new connection: [Errno 111] Connection refused'))
HTTPConnectionPool(host='cutdb.burnham.org', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5a45f70>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='cys.bios.niu.edu', port=80): Max retries exceeded with url: /dbCAN_seq_V1/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5b30df0>, 'Connection to cys.bios.niu.edu timed out. (connect timeout=120)'))
HTTPConnectionPool(host='darcsite.genzentrum.lmu.de', port=80): Max retries exceeded with url: /darc/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5abe3e8>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='datam.i2r.a-star.edu.sg', port=80): Max retries exceeded with url: /ergdbV2/index.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5a4d100>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='datam.i2r.a-star.edu.sg', port=80): Max retries exceeded with url: /kberg/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5a3e520>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='datam.i2r.a-star.edu.sg', port=80): Max retries exceeded with url: /mdpd/index.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5a458b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='dayhoff.generationcp.org', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5ae8af0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='dbcrid.biolead.org', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5a5a910>, 'Connection to dbcrid.biolead.org timed out. (connect timeout=120)'))
HTTPConnectionPool(host='dblep.hupo.org.cn', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5a5a610>, 'Connection to dblep.hupo.org.cn timed out. (connect timeout=120)'))
HTTPConnectionPool(host='dbptm.mbc.nctu.edu.tw', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5b1cb80>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='dcp.rutgers.edu', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5ab2fb8>, 'Connection to dcp.rutgers.edu timed out. (connect timeout=120)'))
HTTPConnectionPool(host='dga.nubic.northwestern.edu', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5a45b68>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='dmdd.org.uk', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5acd400>, 'Connection to dmdd.org.uk timed out. (connect timeout=120)'))
HTTPConnectionPool(host='dmk-brain.ecn.uiowa.edu', port=80): Max retries exceeded with url: /ATGC/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5acd730>, 'Connection to dmk-brain.ecn.uiowa.edu timed out. (connect timeout=120)'))
HTTPConnectionPool(host='dnamethylome.org', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5a45df0>, 'Connection to dnamethylome.org timed out. (connect timeout=120)'))
HTTPConnectionPool(host='dnatraffic.ibb.waw.pl', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5b1c988>, 'Connection to dnatraffic.ibb.waw.pl timed out. (connect timeout=120)'))
HTTPConnectionPool(host='dogvb.big.ac.cn', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5a45d90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='domine.utdallas.edu', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5a45d30>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='donglab.ecnu.edu.cn', port=80): Read timed out. (read timeout=120)
HTTPConnectionPool(host='doop.abc.hu', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5a45d30>: Failed to establish a new connection: [Errno 113] No route to host'))
HTTPConnectionPool(host='drug2gene.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5a45598>, 'Connection to drug2gene.com timed out. (connect timeout=120)'))
HTTPConnectionPool(host='ecoli.naist.jp', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5a4d7c0>, 'Connection to ecoli.naist.jp timed out. (connect timeout=120)'))
HTTPConnectionPool(host='eduliss.bch.ed.ac.uk', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5a3e538>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='eendb.cbi.pku.edu.cn', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5ae8ad8>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='exolocator.eopsf.org', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5a4d7c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='exon.apps.wistar.org', port=80): Max retries exceeded with url: /PolyA_DB/v3 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5acd118>, 'Connection to exon.apps.wistar.org timed out. (connect timeout=120)'))
HTTPConnectionPool(host='eyesite.cryst.bbk.ac.uk', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5acdb08>, 'Connection to eyesite.cryst.bbk.ac.uk timed out. (connect timeout=120)'))
HTTPConnectionPool(host='fantom31p.gsc.riken.jp', port=80): Max retries exceeded with url: /cage/mm5/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5b1c5b0>, 'Connection to fantom31p.gsc.riken.jp timed out. (connect timeout=120)'))
HTTPConnectionPool(host='fgp.huck.psu.edu', port=80): Max retries exceeded with url: /tribedb/index.pl (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5b307f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
HTTPConnectionPool(host='flybrain.neurobio.arizona.edu', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5a4d328>, 'Connection to flybrain.neurobio.arizona.edu timed out. (connect timeout=120)'))
HTTPConnectionPool(host='flysnp.imp.ac.at', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5b30df0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='fmf.igh.cnrs.fr', port=80): Max retries exceeded with url: /infevers/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5abeac0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='foresttree.org', port=80): Max retries exceeded with url: /ftdb (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5a3e9a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='funshift.cgb.ki.se', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5a3edd8>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='gene64.dna.affrc.go.jp', port=80): Max retries exceeded with url: /RPD/main_en.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5a3ebc8>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='genserv.anat.ox.ac.uk', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5ae8058>, 'Connection to genserv.anat.ox.ac.uk timed out. (connect timeout=120)'))
HTTPConnectionPool(host='gold.tugraz.at', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5a4dd90>, 'Connection to gold.tugraz.at timed out. (connect timeout=120)'))
HTTPConnectionPool(host='golgi.gs.dna.affrc.go.jp', port=80): Max retries exceeded with url: /SY-1102/rad/index.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5a3eb50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='gpxmea.gti.ed.ac.uk', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5b1cf58>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='hdbase.org', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5a3e2f8>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='helix-web.stanford.edu', port=80): Max retries exceeded with url: /LPFC/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5a45c88>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='hembase.niddk.nih.gov', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5abe0e8>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='hintdb.hgc.jp', port=80): Max retries exceeded with url: /htp/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5acd370>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='histone.sce.ntu.edu.sg', port=80): Max retries exceeded with url: /SynLethDB/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5abe118>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='hupex.hgpd.jp', port=80): Max retries exceeded with url: /entrance/index.html (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5b30070>, 'Connection to hupex.hgpd.jp timed out. (connect timeout=120)'))
HTTPConnectionPool(host='insilico.charite.de', port=80): Max retries exceeded with url: /supertarget/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5acd658>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='interdom.i2r.a-star.edu.sg', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5a3ee20>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='jbirc.jbic.or.jp', port=80): Max retries exceeded with url: /hinv/evola/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5a4dd00>: Failed to establish a new connection: [Errno 113] No route to host'))
HTTPConnectionPool(host='jjwanglab.org', port=80): Max retries exceeded with url: /dbpshp (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5b1cf28>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='jjwanglab.org', port=80): Max retries exceeded with url: /gwasdb (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5b30d78>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='juncdb.carmelab.huji.ac.il', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5ae8d00>, 'Connection to juncdb.carmelab.huji.ac.il timed out. (connect timeout=120)'))
HTTPConnectionPool(host='kineticdb.protres.ru', port=80): Max retries exceeded with url: /db/index.pl (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5a3e4c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='lcgbase.big.ac.cn', port=80): Max retries exceeded with url: /plastid-LCGbase/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5a3e0a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='lifecenter.sgst.cn', port=80): Max retries exceeded with url: /bodyfluid/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5a3ee68>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='lifecenter.sgst.cn', port=80): Max retries exceeded with url: /dbdepc/index.do (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5a5a460>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='lifecenter.sgst.cn', port=80): Max retries exceeded with url: /hit (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5a3e8b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='locate.imb.uq.edu.au', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5acd4c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='metaref.org', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5a45b08>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='mgb.biocloud.net', port=80): Max retries exceeded with url: /home (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5a45c58>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='mgedb.comp-sysbio.org', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5a45778>: Failed to establish a new connection: [Errno 111] Connection refused'))
HTTPConnectionPool(host='microme.genomics.org.cn', port=80): Max retries exceeded with url: /program/GenoListPERL/index.pl?database=leptolist (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5a3ea00>, 'Connection to microme.genomics.org.cn timed out. (connect timeout=120)'))
HTTPConnectionPool(host='minimotifminer.org%20and%20mnm.engr.uconn.edu', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5b1cbf8>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='mips.gsf.de', port=80): Max retries exceeded with url: /genre/proj/corum/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5b1c6d0>, 'Connection to mips.gsf.de timed out. (connect timeout=120)'))
HTTPConnectionPool(host='mips.gsf.de', port=80): Max retries exceeded with url: /genre/proj/mfungd/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5acdb98>, 'Connection to mips.gsf.de timed out. (connect timeout=120)'))
HTTPConnectionPool(host='mips.gsf.de', port=80): Max retries exceeded with url: /proj/plant/jsf/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5acd2f8>, 'Connection to mips.gsf.de timed out. (connect timeout=120)'))
HTTPConnectionPool(host='mips.gsf.de', port=80): Max retries exceeded with url: /proj/plant/jsf/rice/index.jsp (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5ae8fa0>, 'Connection to mips.gsf.de timed out. (connect timeout=120)'))
HTTPConnectionPool(host='mips.gsf.de', port=80): Max retries exceeded with url: /simap/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5b1c688>, 'Connection to mips.gsf.de timed out. (connect timeout=120)'))
HTTPConnectionPool(host='mips.helmholtz-muenchen.de', port=80): Max retries exceeded with url: /HoPI/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5b30fe8>, 'Connection to mips.helmholtz-muenchen.de timed out. (connect timeout=120)'))
HTTPConnectionPool(host='mips.helmholtz-muenchen.de', port=80): Max retries exceeded with url: /Organ_System_Heterogeneity/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5abebc8>, 'Connection to mips.helmholtz-muenchen.de timed out. (connect timeout=120)'))
HTTPConnectionPool(host='mips.helmholtz-muenchen.de', port=80): Max retries exceeded with url: /plant/athal/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5b1ce08>, 'Connection to mips.helmholtz-muenchen.de timed out. (connect timeout=120)'))
HTTPConnectionPool(host='mips.helmholtz-muenchen.de', port=80): Max retries exceeded with url: /proj/ppi/negatome (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5b1c9e8>, 'Connection to mips.helmholtz-muenchen.de timed out. (connect timeout=120)'))
HTTPConnectionPool(host='mirlab.sysu.edu.cn', port=80): Max retries exceeded with url: /rmbase/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5a3e310>, 'Connection to mirlab.sysu.edu.cn timed out. (connect timeout=120)'))
HTTPConnectionPool(host='mirnamap.mbc.nctu.edu.tw', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5b1c1d8>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='mirtarbase.mbc.nctu.edu.tw', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5b1ce80>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='mirtarbase.mbc.nctu.edu.tw', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5b30208>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='mitodrome.ba.itb.cnr.it', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5abef70>: Failed to establish a new connection: [Errno 111] Connection refused'))
HTTPConnectionPool(host='mmcd.nmrfam.wisc.edu', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5acd730>, 'Connection to mmcd.nmrfam.wisc.edu timed out. (connect timeout=120)'))
HTTPConnectionPool(host='mmdb.iab.keio.ac.jp', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5b1ca30>, 'Connection to mmdb.iab.keio.ac.jp timed out. (connect timeout=120)'))
HTTPConnectionPool(host='mosas.sysu.edu.cn', port=80): Max retries exceeded with url: /utr (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5a3e3d0>, 'Connection to mosas.sysu.edu.cn timed out. (connect timeout=120)'))
HTTPConnectionPool(host='mpss.udel.edu', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5a3ee38>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='mpss.udel.edu', port=80): Max retries exceeded with url: /at/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5a5a328>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='mutdb.org', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5acd160>, 'Connection to mutdb.org timed out. (connect timeout=120)'))
HTTPConnectionPool(host='mvirdb.llnl.gov', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5a3e4c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='narcisse.toulouse.inra.fr', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5ae8aa8>, 'Connection to narcisse.toulouse.inra.fr timed out. (connect timeout=120)'))
HTTPConnectionPool(host='natsdb.cbi.pku.edu.cn', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5b30730>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='nava.liacs.nl', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5ae8820>: Failed to establish a new connection: [Errno 113] No route to host'))
HTTPConnectionPool(host='neobio.cs.pusan.ac.kr', port=80): Max retries exceeded with url: /evog/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5b1cac0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='net.icgeb.org', port=80): Max retries exceeded with url: /benchmark/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5a5a580>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='netbio.bgu.ac.il', port=80): Max retries exceeded with url: /diffnet (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5b1cec8>, 'Connection to netbio.bgu.ac.il timed out. (connect timeout=120)'))
HTTPConnectionPool(host='netbio.bgu.ac.il', port=80): Max retries exceeded with url: /tissuenet/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5b1c8f8>, 'Connection to netbio.bgu.ac.il timed out. (connect timeout=120)'))
HTTPConnectionPool(host='newt-omics.mpi-bn.mpg.de', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5abe2b0>, 'Connection to newt-omics.mpi-bn.mpg.de timed out. (connect timeout=120)'))
HTTPConnectionPool(host='nmr.cmbi.ru.nl', port=80): Max retries exceeded with url: /NRG-CING (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5a3e1f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='nonb.abcc.ncifcrf.gov', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5a3ebb0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='nwsr.smith.man.ac.uk', port=80): Max retries exceeded with url: /pepseeker/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5a4df10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='ogre.mcmaster.ca', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5a4d5e0>, 'Connection to ogre.mcmaster.ca timed out. (connect timeout=120)'))
HTTPConnectionPool(host='oligogenome.stanford.edu', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5b30dc0>, 'Connection to oligogenome.stanford.edu timed out. (connect timeout=120)'))
HTTPConnectionPool(host='omia.angis.org.au', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5a4d298>, 'Connection to omia.angis.org.au timed out. (connect timeout=120)'))
HTTPConnectionPool(host='orion.rnet.missouri.edu', port=80): Max retries exceeded with url: /~nz953/DOMMINO/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5abe610>, 'Connection to orion.rnet.missouri.edu timed out. (connect timeout=120)'))
HTTPConnectionPool(host='oryzasnp.org', port=8080): Max retries exceeded with url: /iric-portal/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5a45628>: Failed to establish a new connection: [Errno 111] Connection refused'))
HTTPConnectionPool(host='oxytricha.princeton.edu', port=80): Max retries exceeded with url: /dimorphism/database.htm (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5b1c1d8>, 'Connection to oxytricha.princeton.edu timed out. (connect timeout=120)'))
HTTPConnectionPool(host='paramecium.cgm.cnrs-gif.fr', port=80): Max retries exceeded with url: /db/index (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5b1cf10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='pedant.gsf.de', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5acddd8>, 'Connection to pedant.gsf.de timed out. (connect timeout=120)'))
HTTPConnectionPool(host='pepcyber.umn.edu', port=80): Max retries exceeded with url: /PPEP/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5a45c70>, 'Connection to pepcyber.umn.edu timed out. (connect timeout=120)'))
HTTPConnectionPool(host='pfd.med.monash.edu.au', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5a4d148>, 'Connection to pfd.med.monash.edu.au timed out. (connect timeout=120)'))
HTTPConnectionPool(host='pid.nci.nih.gov', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5a4da60>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='pidd.math.iastate.edu', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5a4d640>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='pig.vbi.vt.edu', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5a4d568>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='pimp.starflr.info', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5a3e808>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='plantmetabolomics.vrac.iastate.edu', port=80): Max retries exceeded with url: /ver2/index.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5a4d1a8>, 'Connection to plantmetabolomics.vrac.iastate.edu timed out. (connect timeout=120)'))
HTTPConnectionPool(host='plantpis.ba.itb.cnr.it', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5acdb08>: Failed to establish a new connection: [Errno 111] Connection refused'))
HTTPConnectionPool(host='plantrepeats.plantbiology.msu.edu', port=80): Max retries exceeded with url: /index.html (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5ae8778>, 'Connection to plantrepeats.plantbiology.msu.edu timed out. (connect timeout=120)'))
HTTPConnectionPool(host='plantsp.sdsc.edu', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5a3e460>, 'Connection to plantsp.sdsc.edu timed out. (connect timeout=120)'))
HTTPConnectionPool(host='pmap.burnham.org', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5a3ed90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='pmrc.med.mssm.edu', port=9090): Max retries exceeded with url: /QTL/jsp/qtlhome.jsp (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5ae8598>, 'Connection to pmrc.med.mssm.edu timed out. (connect timeout=120)'))
HTTPConnectionPool(host='polbase.neb.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5af5910>, 'Connection to polbase.neb.com timed out. (connect timeout=120)'))
HTTPConnectionPool(host='primerdepot.nci.nih.gov', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5a3ee80>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='prion.bchs.uh.edu', port=80): Max retries exceeded with url: /bp_type/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5a3e6a0>: Failed to establish a new connection: [Errno 113] No route to host'))
HTTPConnectionPool(host='prism.ccbb.ku.edu.tr', port=80): Max retries exceeded with url: /hotregion (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5abefe8>, 'Connection to prism.ccbb.ku.edu.tr timed out. (connect timeout=120)'))
HTTPConnectionPool(host='prism.ccbb.ku.edu.tr', port=80): Max retries exceeded with url: /hotsprint/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5b302e0>, 'Connection to prism.ccbb.ku.edu.tr timed out. (connect timeout=120)'))
HTTPConnectionPool(host='prodom.prabi.fr', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5acd1f0>, 'Connection to prodom.prabi.fr timed out. (connect timeout=120)'))
HTTPConnectionPool(host='prodoric.tu-bs.de', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5ae8ac0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='proportal.mit.edu', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5a3e1c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='protozoadb.biowebdb.org', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5ae8a48>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='psb.kobic.re.kr', port=80): Max retries exceeded with url: /STAP/refinement (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5af5dc0>, 'Connection to psb.kobic.re.kr timed out. (connect timeout=120)'))
HTTPConnectionPool(host='pssrdb.cdfd.org.in', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5a3e520>, 'Connection to pssrdb.cdfd.org.in timed out. (connect timeout=120)'))
HTTPConnectionPool(host='pxgrid.med.monash.edu.au', port=80): Max retries exceeded with url: /polyq/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5a3e040>, 'Connection to pxgrid.med.monash.edu.au timed out. (connect timeout=120)'))
HTTPConnectionPool(host='rapeseed.plantsignal.cn', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5acd8b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='receptome.stanford.edu', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5abeb38>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='regphos.mbc.nctu.edu.tw', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5acd6a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='regtransbase.lbl.gov', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5acdac0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='remap.cisreg.eu', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5b30d60>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='research.imb.uq.edu.au', port=80): Max retries exceeded with url: /RNAdb/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5a459e8>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='rhesusbase.cbi.pku.edu.cn', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5abe6d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='rice.kps.ku.ac.th', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5acdf28>: Failed to establish a new connection: [Errno 111] Connection refused'))
HTTPConnectionPool(host='ricegaas.dna.affrc.go.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5a3edc0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='rloop-v2.bii.a-star.edu.sg', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5a3e310>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='rmd.ncpgr.cn', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5ae8f10>, 'Connection to rmd.ncpgr.cn timed out. (connect timeout=120)'))
HTTPConnectionPool(host='rna-mdb.cas.albany.edu', port=80): Max retries exceeded with url: /RNAmods/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5a45f10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='rnaedit.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5ae8460>, 'Connection to rnaedit.com timed out. (connect timeout=120)'))
HTTPConnectionPool(host='rnp.uthscsa.edu', port=80): Max retries exceeded with url: /rnp/SRPDB/SRPDB.html (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5a3e760>, 'Connection to rnp.uthscsa.edu timed out. (connect timeout=120)'))
HTTPConnectionPool(host='rnp.uthscsa.edu', port=80): Max retries exceeded with url: /rnp/tmRDB/tmRDB.html (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5a3eb08>, 'Connection to rnp.uthscsa.edu timed out. (connect timeout=120)'))
HTTPConnectionPool(host='rnrdb.molbio.su.se', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5b1ca30>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='service.ipr.pdbj.org', port=80): Max retries exceeded with url: /eF-site/index.jsp (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5a5a5c8>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='sevens.cbrc.jp', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5abeb50>, 'Connection to sevens.cbrc.jp timed out. (connect timeout=120)'))
HTTPConnectionPool(host='sirecords.biolead.org', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5a45940>, 'Connection to sirecords.biolead.org timed out. (connect timeout=120)'))
HTTPConnectionPool(host='sirna.sbc.su.se', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5a45400>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='snplogic.org', port=80): Max retries exceeded with url: // (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5a45910>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='snps.tcruzi.org', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5abe220>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='soybase.org', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5b1c7c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
HTTPConnectionPool(host='spliceinfo.mbc.nctu.edu.tw', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5ae8460>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='srnamap.mbc.nctu.edu.tw', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5acd4d8>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='stab.comp-sysbio.org', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5ab2e38>: Failed to establish a new connection: [Errno 111] Connection refused'))
HTTPConnectionPool(host='structuralbiology.cau.edu.cn', port=80): Max retries exceeded with url: /PNRD (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5acd940>, 'Connection to structuralbiology.cau.edu.cn timed out. (connect timeout=120)'))
HTTPConnectionPool(host='structuralbiology.cau.edu.cn', port=80): Max retries exceeded with url: /gossypium/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5a3e2f8>, 'Connection to structuralbiology.cau.edu.cn timed out. (connect timeout=120)'))
HTTPConnectionPool(host='structure.bioc.cam.ac.uk', port=80): Max retries exceeded with url: /platinum (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5ae8c40>, 'Connection to structure.bioc.cam.ac.uk timed out. (connect timeout=120)'))
HTTPConnectionPool(host='swift.cmbi.ru.nl', port=80): Max retries exceeded with url: /gv/facilities/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5bfc8c8>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='syslab.nchu.edu.tw', port=80): Max retries exceeded with url: /DPRP/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5ae84d8>, 'Connection to syslab.nchu.edu.tw timed out. (connect timeout=120)'))
HTTPConnectionPool(host='syslab4.nchu.edu.tw', port=80): Max retries exceeded with url: /CRN (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5abee98>, 'Connection to syslab4.nchu.edu.tw timed out. (connect timeout=120)'))
HTTPConnectionPool(host='systemsbiology.cau.edu.cn', port=80): Max retries exceeded with url: /chromstates (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5abe298>, 'Connection to systemsbiology.cau.edu.cn timed out. (connect timeout=120)'))
HTTPConnectionPool(host='tcruzidb.org', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5bfcee0>, 'Connection to tcruzidb.org timed out. (connect timeout=120)'))
HTTPConnectionPool(host='tpmd.nhri.org.tw', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5ae8718>: Failed to establish a new connection: [Errno 111] Connection refused'))
HTTPConnectionPool(host='ucbase.unimore.it', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5ae8598>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='unitrap.crg.es', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5a45850>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='utrdb.ba.itb.cnr.it', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5abe8e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
HTTPConnectionPool(host='validness.ym.edu.tw', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5b30028>, 'Connection to validness.ym.edu.tw timed out. (connect timeout=120)'))
HTTPConnectionPool(host='viroligo.okstate.edu', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5abeb50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='vita.mbc.nctu.edu.tw', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5ae8148>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='wheat.pw.usda.gov', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5bfcc28>: Failed to establish a new connection: [Errno 111] Connection refused'))
HTTPConnectionPool(host='wu.scbb.pkusz.edu.cn', port=80): Max retries exceeded with url: /wdsp/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5b1c430>, 'Connection to wu.scbb.pkusz.edu.cn timed out. (connect timeout=120)'))
HTTPConnectionPool(host='www-deletion.stanford.edu', port=80): Max retries exceeded with url: /YDPM/YDPM_index.html (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5abe670>, 'Connection to www-deletion.stanford.edu timed out. (connect timeout=120)'))
HTTPConnectionPool(host='www.arachnoserver.org', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5ae8460>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='www.aspergillus-genomes.org.uk', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5abe6b8>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='www.aspgd.org', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5bfc568>, 'Connection to www.aspgd.org timed out. (connect timeout=120)'))
HTTPConnectionPool(host='www.beetlebase.org', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5b1cc58>, 'Connection to www.beetlebase.org timed out. (connect timeout=120)'))
HTTPConnectionPool(host='www.biochem.ucl.ac.uk', port=80): Max retries exceeded with url: /bsm/virus_database/VIDA.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5a457f0>: Failed to establish a new connection: [Errno 113] No route to host'))
HTTPConnectionPool(host='www.bioinfo.org.cn', port=80): Max retries exceeded with url: /NPInter/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5ae81d8>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='www.bioinfo.org.cn', port=80): Max retries exceeded with url: /hptaa/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5acd9b8>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='www.bioinfodatabase.com', port=80): Max retries exceeded with url: /pint/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5ae82f8>, 'Connection to www.bioinfodatabase.com timed out. (connect timeout=120)'))
HTTPConnectionPool(host='www.cangem.org', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5ab2f40>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='www.catma.org', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5b1c550>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='www.cmbi.ru.nl', port=80): Max retries exceeded with url: /phylopat/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5acdce8>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='www.dbali.org', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5ae8058>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='www.domins.org', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5abe9e8>, 'Connection to www.domins.org timed out. (connect timeout=120)'))
HTTPConnectionPool(host='www.eplantsenescence.org', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5acd838>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='www.everest.cs.huji.ac.il', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5ae81f0>, 'Connection to www.everest.cs.huji.ac.il timed out. (connect timeout=120)'))
HTTPConnectionPool(host='www.fusariumdb.org', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5a3e1f0>, 'Connection to www.fusariumdb.org timed out. (connect timeout=120)'))
HTTPConnectionPool(host='www.genestation.org', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5a4db68>, 'Connection to www.genestation.org timed out. (connect timeout=120)'))
HTTPConnectionPool(host='www.genpat.uu.se', port=80): Max retries exceeded with url: /mtDB/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5acd4c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='www.glycostructures.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5b30d90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='www.hpmcd.org', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5b30148>, 'Connection to www.hpmcd.org timed out. (connect timeout=120)'))
HTTPConnectionPool(host='www.igdd.iicb.res.in', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5acd988>: Failed to establish a new connection: [Errno 113] No route to host'))
HTTPConnectionPool(host='www.interferome.org', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5acdf70>, 'Connection to www.interferome.org timed out. (connect timeout=120)'))
HTTPConnectionPool(host='www.ippidb.cdithem.fr', port=80): Max retries exceeded with url: /%20http://www.cdithem.fr/ippidb/v2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5a3e9e8>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='www.mbio.ncsu.edu', port=80): Max retries exceeded with url: /RNaseP/home.html (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5b30280>, 'Connection to www.mbio.ncsu.edu timed out. (connect timeout=120)'))
HTTPConnectionPool(host='www.microrna.org', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5acd5c8>, 'Connection to www.microrna.org timed out. (connect timeout=120)'))
HTTPConnectionPool(host='www.mitoage.org', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5abecd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='www.molecular-systems.org', port=80): Max retries exceeded with url: /csdbase/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5a454a8>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='www.ompdb.org', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5acd850>, 'Connection to www.ompdb.org timed out. (connect timeout=120)'))
HTTPConnectionPool(host='www.pazar.info', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5a4d088>, 'Connection to www.pazar.info timed out. (connect timeout=120)'))
HTTPConnectionPool(host='www.phenomicdb.de', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5a4dfb8>, 'Connection to www.phenomicdb.de timed out. (connect timeout=120)'))
HTTPConnectionPool(host='www.pocketome.org', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5a3e310>, 'Connection to www.pocketome.org timed out. (connect timeout=120)'))
HTTPConnectionPool(host='www.polya-db.org', port=80): Max retries exceeded with url: /v3.beta/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5b30460>, 'Connection to www.polya-db.org timed out. (connect timeout=120)'))
HTTPConnectionPool(host='www.proteus.cs.huji.ac.il', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5b1c898>, 'Connection to www.proteus.cs.huji.ac.il timed out. (connect timeout=120)'))
HTTPConnectionPool(host='www.protonet.cs.huji.ac.il', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5ae81f0>, 'Connection to www.protonet.cs.huji.ac.il timed out. (connect timeout=120)'))
HTTPConnectionPool(host='www.retroryza.org', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5a3e208>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='www.rhesusbase.org', port=80): Max retries exceeded with url: /drugDisc/CAM.jsp (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5acde80>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='www.sevaplasmids.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5a45ac0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='www.sigma54.ca', port=80): Max retries exceeded with url: /microbialclusters/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5ae8820>, 'Connection to www.sigma54.ca timed out. (connect timeout=120)'))
HTTPConnectionPool(host='www.signaling-gateway.org', port=80): Max retries exceeded with url: /molecule/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5acd9d0>: Failed to establish a new connection: [Errno 113] No route to host'))
HTTPConnectionPool(host='www.straininfobreak.ugent.be', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5acd8c8>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='www.unipathway.org', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5abe058>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='www0.nih.go.jp', port=80): Max retries exceeded with url: /mirror/Kinases/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5acd580>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='xbase.warwick.ac.uk', port=80): Max retries exceeded with url: /colibase/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5b1c088>, 'Connection to xbase.warwick.ac.uk timed out. (connect timeout=120)'))
HTTPConnectionPool(host='xray.bmc.uu.se', port=80): Max retries exceeded with url: /hicup/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5acdc70>: Failed to establish a new connection: [Errno 111] Connection refused'))
HTTPConnectionPool(host='yeast.gi.k.u-tokyo.ac.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa5ae8628>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPConnectionPool(host='ypa.csbb.ntu.edu.tw', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa5a456b8>, 'Connection to ypa.csbb.ntu.edu.tw timed out. (connect timeout=120)'))
HTTPSConnectionPool(host='bard.nih.gov', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xa5bfcbe0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPSConnectionPool(host='bhapp.c2b2.columbia.edu', port=443): Max retries exceeded with url: /OnTheFly/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')))
HTTPSConnectionPool(host='bhapp.c2b2.columbia.edu', port=443): Max retries exceeded with url: /PrePPI (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')))
HTTPSConnectionPool(host='bioinfo.imtech.res.in', port=443): Max retries exceeded with url: /manojk/abiofilm/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')))
HTTPSConnectionPool(host='bioinfo.imtech.res.in', port=443): Max retries exceeded with url: /manojk/sigmol (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')))
HTTPSConnectionPool(host='bioinformatics.cs.vt.edu', port=443): Max retries exceeded with url: /cmgs/CMGSDB/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')))
HTTPSConnectionPool(host='bitterdb.agri.huji.ac.il', port=443): Max retries exceeded with url: /dbbitter.php (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')))
HTTPSConnectionPool(host='ccg.epfl.ch', port=443): Max retries exceeded with url: //UCNEbase/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')))
HTTPSConnectionPool(host='ccg.epfl.ch', port=443): Max retries exceeded with url: //htpselex/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')))
HTTPSConnectionPool(host='ccg.epfl.ch', port=443): Max retries exceeded with url: //mga/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')))
HTTPSConnectionPool(host='ccg.epfl.ch', port=443): Max retries exceeded with url: //snp2tfbs/: (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')))
HTTPSConnectionPool(host='cleanex.epfl.ch', port=443): Max retries exceeded with url: // (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xa5ae8238>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPSConnectionPool(host='clustercad.jbei.org%20and%20http', port=443): Max retries exceeded with url: //clustercad.igb.uci.edu (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xa5b300d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPSConnectionPool(host='consurfdb.tau.ac.il', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')))
HTTPSConnectionPool(host='darkinome.org', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xa5a3e310>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPSConnectionPool(host='db.idrblab.org', port=443): Max retries exceeded with url: /varidt/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)')))
HTTPSConnectionPool(host='en.bioinfo.org', port=443): Max retries exceeded with url: /dr.vis (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xa5b1c2f8>: Failed to establish a new connection: [Errno 111] Connection refused'))
HTTPSConnectionPool(host='epd.epfl.ch', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')))
HTTPSConnectionPool(host='fermi.utmb.edu', port=443): Max retries exceeded with url: /SDAP/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')))
HTTPSConnectionPool(host='genes2cognition.org', port=443): Read timed out. (read timeout=120)
HTTPSConnectionPool(host='gwips.ucc.ie', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')))
HTTPSConnectionPool(host='hpo.jax.org', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')))
HTTPSConnectionPool(host='hsb.upf.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')))
HTTPSConnectionPool(host='https', port=443): Max retries exceeded with url: //www.rnacossmos.com/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xa5abee98>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPSConnectionPool(host='hugheslab.ccbr.utoronto.ca', port=443): Max retries exceeded with url: /databases/rbpdb/ (Caused by SSLError(SSLError(1, '[SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:1123)')))
HTTPSConnectionPool(host='kbdock.loria.fr', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')))
HTTPSConnectionPool(host='line1.bioapps.biozentrum.uni-wuerzburg.de', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')))
HTTPSConnectionPool(host='lynx.ci.uchicago.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError("hostname 'lynx.ci.uchicago.edu' doesn't match either of 'www.cri.uchicago.edu', '*.bsd.uchicago.edu', '*.cri.uchicago.edu', '*.uchicago.edu', 'inrgdb.org'")))
HTTPSConnectionPool(host='meg.colostate.edu', port=443): Max retries exceeded with url: /MEGaRes/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)')))
HTTPSConnectionPool(host='memmorf.hegelab.org', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1123)')))
HTTPSConnectionPool(host='metalpdb.cerm.unifi.it', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')))
HTTPSConnectionPool(host='metexplore.toulouse.inrae.fr', port=443): Max retries exceeded with url: /trypanocyc/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')))
HTTPSConnectionPool(host='ndb.rice.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')))
HTTPSConnectionPool(host='pepx.switchlab.org', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)')))
HTTPSConnectionPool(host='pitdb.sbcs.qmul.ac.uk', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1123)')))
HTTPSConnectionPool(host='planosphere.stowers.org', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')))
HTTPSConnectionPool(host='ppdb.agr.gifu-u.ac.jp', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')))
HTTPSConnectionPool(host='proteomescout.wustl.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1123)')))
HTTPSConnectionPool(host='rdb.vlifescience.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xa5a459b8>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPSConnectionPool(host='rnavlab.utep.edu', port=443): Max retries exceeded with url: /database (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')))
HTTPSConnectionPool(host='sporeweb.molgenrug.nl', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError("hostname 'sporeweb.molgenrug.nl' doesn't match 'molgenrug.nl'")))
HTTPSConnectionPool(host='toxico.nibiohn.go.jp', port=443): Max retries exceeded with url: /english/index.html (Caused by SSLError(SSLError(1, '[SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:1123)')))
HTTPSConnectionPool(host='v5.greenphyl.org', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xa5b306e8>, 'Connection to v5.greenphyl.org timed out. (connect timeout=120)'))
HTTPSConnectionPool(host='viperdb.scripps.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')))
HTTPSConnectionPool(host='www-is.biotoul.fr', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')))
HTTPSConnectionPool(host='www-snorna.biotoul.fr', port=443): Max retries exceeded with url: // (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1123)')))
HTTPSConnectionPool(host='www.geneweaver.org', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')))
HTTPSConnectionPool(host='www.hmtdb.uniba.it', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')))
HTTPSConnectionPool(host='www.iitm.ac.in', port=443): Max retries exceeded with url: /bioinfo/ProTherm2/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')))
HTTPSConnectionPool(host='www.imtech.res.in', port=443): Max retries exceeded with url: /raghava/antigendb (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')))
HTTPSConnectionPool(host='www.imtech.res.in', port=443): Max retries exceeded with url: /raghava/bcipep/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')))
HTTPSConnectionPool(host='www.imtech.res.in', port=443): Max retries exceeded with url: /raghava/haptendb/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')))
HTTPSConnectionPool(host='www.imtech.res.in', port=443): Max retries exceeded with url: /raghava/mhcbn/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')))
HTTPSConnectionPool(host='www.imtech.res.in', port=443): Max retries exceeded with url: /raghava/prrdb/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')))
HTTPSConnectionPool(host='www.internationalgenome.org', port=443): Max retries exceeded with url: /data-portal (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1123)')))
HTTPSConnectionPool(host='www.jncasr.ac.in', port=443): Max retries exceeded with url: /cremofac/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')))
HTTPSConnectionPool(host='www.medicalgenomics.org', port=443): Max retries exceeded with url: /celllinenavigator/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)')))
HTTPSConnectionPool(host='www.spatialomics.org', port=443): Max retries exceeded with url: /SpatialDB/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1123)')))
HTTPSConnectionPool(host='www.tumorfusions.org', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')))
HTTPSConnectionPool(host='www.viprbrc.org', port=443): Read timed out. (read timeout=120)
HTTPSConnectionPool(host='www.wikigenes.orgunipub', port=443): Max retries exceeded with url: /HCAD (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xa5a3eaf0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
HTTPSConnectionPool(host='www.wzgenomics.cn', port=443): Max retries exceeded with url: /mirdnmr/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1123)')))
HTTPSConnectionPool(host='zifdb.msi.umn.edu', port=8444): Max retries exceeded with url: /ZiFDB/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xa5a45fa0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
Internal Server Error
Invalid URL 'dwishart@ualberta.ca': No schema supplied. Perhaps you meant http://dwishart@ualberta.ca?
Invalid URL 'imodulondb.com': No schema supplied. Perhaps you meant http://imodulondb.com?
Invalid URL 'www.RJunBase.org': No schema supplied. Perhaps you meant http://www.RJunBase.org?
Invalid URL 'www.broadinstitute.org/mitocarta': No schema supplied. Perhaps you meant http://www.broadinstitute.org/mitocarta?
Invalid URL 'www.ncbi.nlm.nih.gov/genbank/': No schema supplied. Perhaps you meant http://www.ncbi.nlm.nih.gov/genbank/?
NOT FOUND
No connection adapters were found for '(http://www.licpathway.net/KnockTF/index.html'
No connection adapters were found for 'ftp://ftp.isrec.isb-sib.ch/pub/databases/'
Not Acceptable
Not Found
OK
Ok
Precondition Failed
Service Temporarily Unavailable
Service Unavailable
Unauthorized
